app {
  log_level = "debug"
  spark {
    input_file_path = "src/main/resources/ct_rr.csv"
    output_file_path = "src/main/resources/output"
    master = "local[*]"
    app_name = "SparkAssignment"
    cohort {
        week_date = "2018-12-31"
        no_of_weeks = 3
    }
  }
}